#Parvo Script
#WGSP01
```{r}
WGSP01_S1PARVO <- read.csv("C://Users//thoma//OneDrive - Murdoch University//Desktop//PhD 2021//Study 2 and 3//AAADATA//Participants//WGSP01//Session1//Parvo//WGSP01_S1.csv")
WGSP01_S2PARVO <- read.csv("C://Users//thoma//OneDrive - Murdoch University//Desktop//PhD 2021//Study 2 and 3//AAADATA//Participants//WGSP01//Session2//Parvo//WGSP01_S2.csv")
WGSP01_S3PARVO <- read.csv("C://Users//thoma//OneDrive - Murdoch University//Desktop//PhD 2021//Study 2 and 3//AAADATA//Participants//WGSP01//Session3//Parvo//WGSP01_S3.csv")
WGSP01_S4PARVO <- read.csv("C://Users//thoma//OneDrive - Murdoch University//Desktop//PhD 2021//Study 2 and 3//AAADATA//Participants//WGSP01//Session4//Parvo//WGSP01_S4.csv")
```

##Session 1
```{r}
WGSP01_S1PARVOc <- WGSP01_S1PARVO%>%
  mutate(participant = "P1")%>%
  mutate(session = 1)%>%
  mutate(BFR = "YES")%>%
  mutate(AOP = 88)%>%
  mutate(speed = "FW")%>%
  mutate(km_h = 6.7)
  
```

##Session 2
```{r}
WGSP01_S2PARVOc <- WGSP01_S2PARVO%>%
  mutate(participant = "P1")%>%
  mutate(session = 2)%>%
  mutate(BFR = "NO")%>%
  mutate(AOP = 0)%>%
  mutate(speed = "FW")%>%
  mutate(km_h = 6.7)
```

##Session 3
```{r}
WGSP01_S3PARVOc <- WGSP01_S3PARVO%>%
  mutate(participant = "P1")%>%
  mutate(session = 3)%>%
  mutate(BFR = "YES")%>%
  mutate(AOP = 88)%>%
  mutate(speed = "SW")%>%
  mutate(km_h = 5.2)
```

##Session 4
```{r}
WGSP01_S4PARVOc <- WGSP01_S4PARVO%>%
  mutate(participant = "P1")%>%
  mutate(session = 4)%>%
  mutate(BFR = "NO")%>%
  mutate(AOP = 0)%>%
  mutate(speed = "SW")%>%
  mutate(km_h = 5.2)
```

```{r}
WGSP01_bind <- rbind(WGSP01_S1PARVOc,WGSP01_S2PARVOc,WGSP01_S3PARVOc,WGSP01_S4PARVOc)%>%
  mutate(age = 26)%>%
  mutate(sex = "male")
```

#WGSP02
```{r}
WGSP02_S1PARVO <- read.csv("C://Users//thoma//OneDrive - Murdoch University//Desktop//PhD 2021//Study 2 and 3//AAADATA//Participants//WGSP02//Session1//Parvo//WGSP02_S1.csv")
WGSP02_S2PARVO <- read.csv("C://Users//thoma//OneDrive - Murdoch University//Desktop//PhD 2021//Study 2 and 3//AAADATA//Participants//WGSP02//Session2//Parvo//WGSP02_S2.csv")
WGSP02_S3PARVO <- read.csv("C://Users//thoma//OneDrive - Murdoch University//Desktop//PhD 2021//Study 2 and 3//AAADATA//Participants//WGSP02//Session3//Parvo//WGSP02_S3.csv")
WGSP02_S4PARVO <- read.csv("C://Users//thoma//OneDrive - Murdoch University//Desktop//PhD 2021//Study 2 and 3//AAADATA//Participants//WGSP02//Session4//Parvo//WGSP02_S4.csv")
```

##Session 1
```{r}
WGSP02_S1PARVOc <- WGSP02_S1PARVO%>%
  mutate(participant = "P2")%>%
  mutate(session = 1)%>%
  mutate(BFR = "YES")%>%
  mutate(AOP = 101)%>%
  mutate(speed = "SW")%>%
  mutate(km_h = 5.5)
  
```

##Session 2
```{r}
WGSP02_S2PARVOc <- WGSP02_S2PARVO%>%
  mutate(participant = "P2")%>%
  mutate(session = 2)%>%
  mutate(BFR = "NO")%>%
  mutate(AOP = 0)%>%
  mutate(speed = "SW")%>%
  mutate(km_h = 5.5)
```

##Session 3
```{r}
WGSP02_S3PARVOc <- WGSP02_S3PARVO%>%
  mutate(participant = "P2")%>%
  mutate(session = 3)%>%
  mutate(BFR = "YES")%>%
  mutate(AOP = 101)%>%
  mutate(speed = "FW")%>%
  mutate(km_h = 7.1)
```

##Session 4
```{r}
WGSP02_S4PARVOc <- WGSP02_S4PARVO%>%
  mutate(participant = "P2")%>%
  mutate(session = 4)%>%
  mutate(BFR = "NO")%>%
  mutate(AOP = 0)%>%
  mutate(speed = "FW")%>%
  mutate(km_h = 7.1)
```

```{r}
WGSP02_bind <- rbind(WGSP02_S1PARVOc,WGSP02_S2PARVOc,WGSP02_S3PARVOc,WGSP02_S4PARVOc)%>%
  mutate(age = 25)%>%
  mutate(sex = "male")
```

#WGSP04
```{r}
WGSP04_S1PARVO <- read.csv("C://Users//thoma//OneDrive - Murdoch University//Desktop//PhD 2021//Study 2 and 3//AAADATA//Participants//WGSP04//Session1//Parvo//WGSP04_S1.csv")
WGSP04_S2PARVO <- read.csv("C://Users//thoma//OneDrive - Murdoch University//Desktop//PhD 2021//Study 2 and 3//AAADATA//Participants//WGSP04//Session2//Parvo//WGSP04_S2.csv")
WGSP04_S3PARVO <- read.csv("C://Users//thoma//OneDrive - Murdoch University//Desktop//PhD 2021//Study 2 and 3//AAADATA//Participants//WGSP04//Session3//Parvo//WGSP04_S3.csv")
WGSP04_S4PARVO <- read.csv("C://Users//thoma//OneDrive - Murdoch University//Desktop//PhD 2021//Study 2 and 3//AAADATA//Participants//WGSP04//Session4//Parvo//WGSP04_S4.csv")
```

##Session 1
```{r}
WGSP04_S1PARVOc <- WGSP04_S1PARVO%>%
  mutate(participant = "P4")%>%
  mutate(session = 1)%>%
  mutate(BFR = "YES")%>%
  mutate(AOP = 102)%>%
  mutate(speed = "SW")%>%
  mutate(km_h = 5.3)
  
```

##Session 2
```{r}
WGSP04_S2PARVOc <- WGSP04_S2PARVO%>%
  mutate(participant = "P4")%>%
  mutate(session = 2)%>%
  mutate(BFR = "NO")%>%
  mutate(AOP = 0)%>%
  mutate(speed = "SW")%>%
  mutate(km_h = 5.3)
```

##Session 3
```{r}
WGSP04_S3PARVOc <- WGSP04_S3PARVO%>%
  mutate(participant = "P4")%>%
  mutate(session = 3)%>%
  mutate(BFR = "YES")%>%
  mutate(AOP = 102)%>%
  mutate(speed = "FW")%>%
  mutate(km_h = 6.8)
```

##Session 4
```{r}
WGSP04_S4PARVOc <- WGSP04_S4PARVO%>%
  mutate(participant = "P4")%>%
  mutate(session = 4)%>%
  mutate(BFR = "NO")%>%
  mutate(AOP = 0)%>%
  mutate(speed = "FW")%>%
  mutate(km_h = 6.8)
```

```{r}
WGSP04_bind <- rbind(WGSP04_S1PARVOc,WGSP04_S2PARVOc,WGSP04_S3PARVOc,WGSP04_S4PARVOc)%>%
  mutate(age = 29)%>%
  mutate(sex = "female")
```

#WGSP06
```{r}
WGSP06_S1PARVO <- read.csv("C://Users//thoma//OneDrive - Murdoch University//Desktop//PhD 2021//Study 2 and 3//AAADATA//Participants//WGSP06//Session1//Parvo//WGSP06_S1.csv")
WGSP06_S2PARVO <- read.csv("C://Users//thoma//OneDrive - Murdoch University//Desktop//PhD 2021//Study 2 and 3//AAADATA//Participants//WGSP06//Session2//Parvo//WGSP06_S2.csv")
WGSP06_S3PARVO <- read.csv("C://Users//thoma//OneDrive - Murdoch University//Desktop//PhD 2021//Study 2 and 3//AAADATA//Participants//WGSP06//Session3//Parvo//WGSP06_S3.csv")
WGSP06_S4PARVO <- read.csv("C://Users//thoma//OneDrive - Murdoch University//Desktop//PhD 2021//Study 2 and 3//AAADATA//Participants//WGSP06//Session4//Parvo//WGSP06_S4.csv")
```

##Session 1
```{r}
WGSP06_S1PARVOc <- WGSP06_S1PARVO%>%
  mutate(participant = "P6")%>%
  mutate(session = 1)%>%
  mutate(BFR = "YES")%>%
  mutate(AOP = 115)%>%
  mutate(speed = "SW")%>%
  mutate(km_h = 5.3)
  
```

##Session 2
```{r}
WGSP06_S2PARVOc <- WGSP06_S2PARVO%>%
  mutate(participant = "P6")%>%
  mutate(session = 2)%>%
  mutate(BFR = "NO")%>%
  mutate(AOP = 0)%>%
  mutate(speed = "SW")%>%
  mutate(km_h = 5.3)
```

##Session 3
```{r}
WGSP06_S3PARVOc <- WGSP06_S3PARVO%>%
  mutate(participant = "P6")%>%
  mutate(session = 3)%>%
  mutate(BFR = "YES")%>%
  mutate(AOP = 115)%>%
  mutate(speed = "FW")%>%
  mutate(km_h = 6.8)
```

##Session 4
```{r}
WGSP06_S4PARVOc <- WGSP06_S4PARVO%>%
  mutate(participant = "P6")%>%
  mutate(session = 4)%>%
  mutate(BFR = "NO")%>%
  mutate(AOP = 0)%>%
  mutate(speed = "FW")%>%
  mutate(km_h = 6.8)
```

```{r}
WGSP06_bind <- rbind(WGSP06_S1PARVOc,WGSP06_S2PARVOc,WGSP06_S3PARVOc,WGSP06_S4PARVOc)%>%
  mutate(age = 30)%>%
  mutate(sex = "male")
```

#WGSP07
```{r}
WGSP07_S1PARVO <- read.csv("C://Users//thoma//OneDrive - Murdoch University//Desktop//PhD 2021//Study 2 and 3//AAADATA//Participants//WGSP07//Session1//Parvo//WGSP07_S1.csv")
WGSP07_S2PARVO <- read.csv("C://Users//thoma//OneDrive - Murdoch University//Desktop//PhD 2021//Study 2 and 3//AAADATA//Participants//WGSP07//Session2//Parvo//WGSP07_S2.csv")
WGSP07_S3PARVO <- read.csv("C://Users//thoma//OneDrive - Murdoch University//Desktop//PhD 2021//Study 2 and 3//AAADATA//Participants//WGSP07//Session3//Parvo//WGSP07_S3.csv")
WGSP07_S4PARVO <- read.csv("C://Users//thoma//OneDrive - Murdoch University//Desktop//PhD 2021//Study 2 and 3//AAADATA//Participants//WGSP07//Session4//Parvo//WGSP07_S4.csv")
```

##Session 1
```{r}
WGSP07_S1PARVOc <- WGSP07_S1PARVO%>%
  mutate(participant = "P7")%>%
  mutate(session = 1)%>%
  mutate(BFR = "YES")%>%
  mutate(AOP = 102)%>%
  mutate(speed = "SW")%>%
  mutate(km_h = 4.9)
  
```

##Session 2
```{r}
WGSP07_S2PARVOc <- WGSP07_S2PARVO%>%
  mutate(participant = "P7")%>%
  mutate(session = 2)%>%
  mutate(BFR = "NO")%>%
  mutate(AOP = 0)%>%
  mutate(speed = "SW")%>%
  mutate(km_h = 4.9)
```

##Session 3
```{r}
WGSP07_S3PARVOc <- WGSP07_S3PARVO%>%
  mutate(participant = "P7")%>%
  mutate(session = 3)%>%
  mutate(BFR = "YES")%>%
  mutate(AOP = 102)%>%
  mutate(speed = "FW")%>%
  mutate(km_h = 6.3)
```

##Session 4
```{r}
WGSP07_S4PARVOc <- WGSP07_S4PARVO%>%
  mutate(participant = "P7")%>%
  mutate(session = 4)%>%
  mutate(BFR = "NO")%>%
  mutate(AOP = 0)%>%
  mutate(speed = "FW")%>%
  mutate(km_h = 6.3)
```

```{r}
WGSP07_bind <- rbind(WGSP07_S1PARVOc,WGSP07_S2PARVOc,WGSP07_S3PARVOc,WGSP07_S4PARVOc)%>%
  mutate(age = 23)%>%
  mutate(sex = "male")
```

#WGSP09
```{r}
WGSP09_S1PARVO <- read.csv("C://Users//thoma//OneDrive - Murdoch University//Desktop//PhD 2021//Study 2 and 3//AAADATA//Participants//WGSP09//Session1//Parvo//WGSP09_S1.csv")
WGSP09_S2PARVO <- read.csv("C://Users//thoma//OneDrive - Murdoch University//Desktop//PhD 2021//Study 2 and 3//AAADATA//Participants//WGSP09//Session2//Parvo//WGSP09_S2.csv")
WGSP09_S3PARVO <- read.csv("C://Users//thoma//OneDrive - Murdoch University//Desktop//PhD 2021//Study 2 and 3//AAADATA//Participants//WGSP09//Session3//Parvo//WGSP09_S3.csv")
WGSP09_S4PARVO <- read.csv("C://Users//thoma//OneDrive - Murdoch University//Desktop//PhD 2021//Study 2 and 3//AAADATA//Participants//WGSP09//Session4//Parvo//WGSP09_S4.csv")
```

##Session 1
```{r}
WGSP09_S1PARVOc <- WGSP09_S1PARVO%>%
  mutate(participant = "P9")%>%
  mutate(session = 1)%>%
  mutate(BFR = "YES")%>%
  mutate(AOP = 108)%>%
  mutate(speed = "FW")%>%
  mutate(km_h = 7.0)
  
```

##Session 2
```{r}
WGSP09_S2PARVOc <- WGSP09_S2PARVO%>%
  mutate(participant = "P9")%>%
  mutate(session = 2)%>%
  mutate(BFR = "NO")%>%
  mutate(AOP = 0)%>%
  mutate(speed = "FW")%>%
  mutate(km_h = 7.0)
```

##Session 3
```{r}
WGSP09_S3PARVOc <- WGSP09_S3PARVO%>%
  mutate(participant = "P9")%>%
  mutate(session = 3)%>%
  mutate(BFR = "YES")%>%
  mutate(AOP = 108)%>%
  mutate(speed = "SW")%>%
  mutate(km_h = 5.5)
```

##Session 4
```{r}
WGSP09_S4PARVOc <- WGSP09_S4PARVO%>%
  mutate(participant = "P9")%>%
  mutate(session = 4)%>%
  mutate(BFR = "NO")%>%
  mutate(AOP = 0)%>%
  mutate(speed = "SW")%>%
  mutate(km_h = 5.5)
```

```{r}
WGSP09_bind <- rbind(WGSP09_S1PARVOc,WGSP09_S2PARVOc,WGSP09_S3PARVOc,WGSP09_S4PARVOc)%>%
  mutate(age = 29)%>%
  mutate(sex = "male")
```

#WGSP12
```{r}
WGSP12_S1PARVO <- read.csv("C://Users//thoma//OneDrive - Murdoch University//Desktop//PhD 2021//Study 2 and 3//AAADATA//Participants//WGSP12//Session1//Parvo//WGSP012_S1.csv")
WGSP12_S2PARVO <- read.csv("C://Users//thoma//OneDrive - Murdoch University//Desktop//PhD 2021//Study 2 and 3//AAADATA//Participants//WGSP12//Session2//Parvo//WGSP012_S2.csv")
WGSP12_S3PARVO <- read.csv("C://Users//thoma//OneDrive - Murdoch University//Desktop//PhD 2021//Study 2 and 3//AAADATA//Participants//WGSP12//Session3//Parvo//WGSP012_S3.csv")
WGSP12_S4PARVO <- read.csv("C://Users//thoma//OneDrive - Murdoch University//Desktop//PhD 2021//Study 2 and 3//AAADATA//Participants//WGSP12//Session4//Parvo//WGSP012_S4.csv")
```

##Session 1
```{r}
WGSP12_S1PARVOc <- WGSP12_S1PARVO%>%
  mutate(participant = "P12")%>%
  mutate(session = 1)%>%
  mutate(BFR = "YES")%>%
  mutate(AOP = 104)%>%
  mutate(speed = "FW")%>%
  mutate(km_h = 6.1)
  
```

##Session 2
```{r}
WGSP12_S2PARVOc <- WGSP12_S2PARVO%>%
  mutate(participant = "P12")%>%
  mutate(session = 2)%>%
  mutate(BFR = "NO")%>%
  mutate(AOP = 0)%>%
  mutate(speed = "FW")%>%
  mutate(km_h = 6.1)
```

##Session 3
```{r}
WGSP12_S3PARVOc <- WGSP12_S3PARVO%>%
  mutate(participant = "P12")%>%
  mutate(session = 3)%>%
  mutate(BFR = "YES")%>%
  mutate(AOP = 104)%>%
  mutate(speed = "SW")%>%
  mutate(km_h = 4.8)
```

##Session 4
```{r}
WGSP12_S4PARVOc <- WGSP12_S4PARVO%>%
  mutate(participant = "P12")%>%
  mutate(session = 4)%>%
  mutate(BFR = "NO")%>%
  mutate(AOP = 0)%>%
  mutate(speed = "SW")%>%
  mutate(km_h = 4.8)
```

```{r}
WGSP12_bind <- rbind(WGSP12_S1PARVOc,WGSP12_S2PARVOc,WGSP12_S3PARVOc,WGSP12_S4PARVOc)%>%
  mutate(age = 23)%>%
  mutate(sex = "male")
```

##Study Bind
```{r}
Study2PARVOBIND <- rbind(WGSP01_bind,WGSP02_bind,WGSP04_bind,WGSP06_bind,WGSP07_bind,WGSP09_bind,WGSP12_bind)
```

```{r}
write.csv(Study2PARVOBIND,"C:\\Users\\thoma\\OneDrive - Murdoch University\\Desktop\\PhD 2021\\Study 2 and 3\\AAADATA\\Main CSV sheets\\RAW_PARVO_DATA(04-11-2021).csv",row.names=FALSE)
```

#Summary
```{r}
VESUM <- Study2PARVOBIND%>%
summarySE(measurevar = "VE", groupvar =c("speed","BFR","participant"), na.rm = TRUE, conf.interval = 0.95, .drop = TRUE)
```

