#WGSP01
```{r}
WGSP01_S1SUB <- read.csv("C://Users//thoma//OneDrive - Murdoch University//Desktop//PhD 2021//Study 2 and 3//AAADATA//Participants//WGSP01//Session1//Perceptual//sub_measures.CSV")
WGSP01_S2SUB <- read.csv("C://Users//thoma//OneDrive - Murdoch University//Desktop//PhD 2021//Study 2 and 3//AAADATA//Participants//WGSP01//Session2//Perceptual//sub_measures.CSV")
WGSP01_S3SUB <- read.csv("C://Users//thoma//OneDrive - Murdoch University//Desktop//PhD 2021//Study 2 and 3//AAADATA//Participants//WGSP01//Session3//Perceptual//sub_measures.CSV")
WGSP01_S4SUB <- read.csv("C://Users//thoma//OneDrive - Murdoch University//Desktop//PhD 2021//Study 2 and 3//AAADATA//Participants//WGSP01//Session4//Perceptual//sub_measures.CSV")
```

#Session 1
```{r}
WGSP01_S1SUB <- WGSP01_S1SUB%>%
  mutate(session = 1)%>%
  mutate(participant = "P1")%>%
  mutate(BFR = "YES")%>%
  mutate(AOP = 88)%>%
  mutate(speed = "FW")%>%
  mutate(km_h = 6.7)%>%
  mutate(type = "FWBFR")
```

#Session 2
```{r}
WGSP01_S2SUB <- WGSP01_S2SUB%>%
  mutate(session = 2)%>%
  mutate(participant = "P1")%>%
  mutate(BFR = "NO")%>%
  mutate(AOP = 0)%>%
  mutate(speed = "FW")%>%
  mutate(km_h = 6.7)%>%
  mutate(type = "FW")
```

#Session 3
```{r}
WGSP01_S3SUB <- WGSP01_S3SUB%>%
  mutate(session = 3)%>%
  mutate(participant = "P1")%>%
  mutate(BFR = "YES")%>%
  mutate(AOP = 88)%>%
  mutate(speed = "SW")%>%
  mutate(km_h = 5.2)%>%
  mutate(type = "SWBFR")
```

#Sesion 4
```{r}
WGSP01_S4SUB <- WGSP01_S4SUB%>%
  mutate(session = 4)%>%
  mutate(participant = "P1")%>%
  mutate(BFR = "NO")%>%
  mutate(AOP = 0)%>%
  mutate(speed = "SW")%>%
  mutate(km_h = 5.2)%>%
  mutate(type = "SW")
```

```{r}
WGSP01SUB <- rbind(WGSP01_S1SUB,WGSP01_S2SUB,WGSP01_S3SUB,WGSP01_S4SUB)
```

#WGSP02
```{r}
WGSP02_S1SUB <- read.csv("C://Users//thoma//OneDrive - Murdoch University//Desktop//PhD 2021//Study 2 and 3//AAADATA//Participants//WGSP02//Session1//Perceptual//sub_measures.CSV")
WGSP02_S2SUB <- read.csv("C://Users//thoma//OneDrive - Murdoch University//Desktop//PhD 2021//Study 2 and 3//AAADATA//Participants//WGSP02//Session2//Perceptual//sub_measures.CSV")
WGSP02_S3SUB <- read.csv("C://Users//thoma//OneDrive - Murdoch University//Desktop//PhD 2021//Study 2 and 3//AAADATA//Participants//WGSP02//Session3//Perceptual//sub_measures.CSV")
WGSP02_S4SUB <- read.csv("C://Users//thoma//OneDrive - Murdoch University//Desktop//PhD 2021//Study 2 and 3//AAADATA//Participants//WGSP02//Session4//Perceptual//sub_measures.CSV")
```

#Session 1
```{r}
WGSP02_S1SUB <- WGSP02_S1SUB%>%
 mutate(session = 1)%>%
  mutate(participant = "P2")%>%
  mutate(BFR = "YES")%>%
  mutate(AOP = 101)%>%
  mutate(speed = "SW")%>%
  mutate(km_h = 5.5)%>%
  mutate(type = "SWBFR")
```

#Session 2
```{r}
WGSP02_S2SUB <- WGSP02_S2SUB%>%
  mutate(session = 2)%>%
  mutate(participant = "P2")%>%
  mutate(BFR = "NO")%>%
  mutate(AOP = 0)%>%
  mutate(speed = "SW")%>%
  mutate(km_h = 5.5)%>%
  mutate(type = "SW")
```

#Session 3
```{r}
WGSP02_S3SUB <- WGSP02_S3SUB%>%
  mutate(session = 3)%>%
  mutate(participant = "P2")%>%
  mutate(BFR = "YES")%>%
  mutate(AOP = 101)%>%
  mutate(speed = "FW")%>%
  mutate(km_h = 7.1)%>%
  mutate(type = "FWBFR")
```

#Sesion 4
```{r}
WGSP02_S4SUB <- WGSP02_S4SUB%>%
 mutate(session = 4)%>%
  mutate(participant = "P2")%>%
  mutate(BFR = "NO")%>%
  mutate(AOP = 0)%>%
  mutate(speed = "FW")%>%
  mutate(km_h = 7.1)%>%
  mutate(type = "FW")  
```

```{r}
WGSP02SUB <- rbind(WGSP02_S1SUB,WGSP02_S2SUB,WGSP02_S3SUB,WGSP02_S4SUB)
```

#WGSP03
```{r}
WGSP03_S1SUB <- read.csv("C://Users//thoma//OneDrive - Murdoch University//Desktop//PhD 2021//Study 2 and 3//AAADATA//Participants//WGSP03//Session1//Perceptual//sub_measures.CSV")
WGSP03_S2SUB <- read.csv("C://Users//thoma//OneDrive - Murdoch University//Desktop//PhD 2021//Study 2 and 3//AAADATA//Participants//WGSP03//Session2//Perceptual//sub_measures.CSV")
WGSP03_S3SUB <- read.csv("C://Users//thoma//OneDrive - Murdoch University//Desktop//PhD 2021//Study 2 and 3//AAADATA//Participants//WGSP03//Session3//Perceptual//sub_measures.CSV")
WGSP03_S4SUB <- read.csv("C://Users//thoma//OneDrive - Murdoch University//Desktop//PhD 2021//Study 2 and 3//AAADATA//Participants//WGSP03//Session4//Perceptual//sub_measures.CSV")
```

#Session 1
```{r}
WGSP03_S1SUB <- WGSP03_S1SUB%>%
 mutate(session = 1)%>%
  mutate(participant = "P3")%>%
  mutate(BFR = "YES")%>%
  mutate(AOP = 90)%>%
  mutate(speed = "FW")%>%
  mutate(km_h = 5.7)%>%
  mutate(type = "FWBFR")
```

#Session 2
```{r}
WGSP03_S2SUB <- WGSP03_S2SUB%>%
  mutate(session = 2)%>%
  mutate(participant = "P3")%>%
  mutate(BFR = "NO")%>%
  mutate(AOP = 0)%>%
  mutate(speed = "FW")%>%
  mutate(km_h = 5.7)%>%
  mutate(type = "FW")
```

#Session 3
```{r}
WGSP03_S3SUB <- WGSP03_S3SUB%>%
  mutate(session = 3)%>%
  mutate(participant = "P3")%>%
  mutate(BFR = "YES")%>%
  mutate(AOP = 90)%>%
  mutate(speed = "SW")%>%
  mutate(km_h = 4.4)%>%
mutate(type = "SWBFR")
```

#Sesion 4
```{r}
WGSP03_S4SUB <- WGSP03_S4SUB%>%
  mutate(session = 4)%>%
  mutate(participant = "P3")%>%
  mutate(BFR = "NO")%>%
  mutate(AOP = 0)%>%
  mutate(speed = "SW")%>%
  mutate(km_h = 4.4)%>%
  mutate(type = "SW")
```

```{r}
WGSP03SUB <- rbind(WGSP03_S1SUB,WGSP03_S2SUB,WGSP03_S3SUB,WGSP03_S4SUB)
```

#WGSP04
```{r}
WGSP04_S1SUB <- read.csv("C://Users//thoma//OneDrive - Murdoch University//Desktop//PhD 2021//Study 2 and 3//AAADATA//Participants//WGSP04//Session1//Perceptual//sub_measures.CSV")
WGSP04_S2SUB <- read.csv("C://Users//thoma//OneDrive - Murdoch University//Desktop//PhD 2021//Study 2 and 3//AAADATA//Participants//WGSP04//Session2//Perceptual//sub_measures.CSV")
WGSP04_S3SUB <- read.csv("C://Users//thoma//OneDrive - Murdoch University//Desktop//PhD 2021//Study 2 and 3//AAADATA//Participants//WGSP04//Session3//Perceptual//sub_measures.CSV")
WGSP04_S4SUB <- read.csv("C://Users//thoma//OneDrive - Murdoch University//Desktop//PhD 2021//Study 2 and 3//AAADATA//Participants//WGSP04//Session4//Perceptual//sub_measures.CSV")
```

#Session 1
```{r}
WGSP04_S1SUB <- WGSP04_S1SUB%>%
 mutate(session = 1)%>%
  mutate(participant = "P4")%>%
  mutate(BFR = "YES")%>%
  mutate(AOP = 102)%>%
  mutate(speed = "SW")%>%
  mutate(km_h = 5.3)%>%
  mutate(type = "SWBFR")
```

#Session 2
```{r}
WGSP04_S2SUB <- WGSP04_S2SUB%>%
  mutate(session = 2)%>%
  mutate(participant = "P4")%>%
  mutate(BFR = "NO")%>%
  mutate(AOP = 0)%>%
  mutate(speed = "SW")%>%
  mutate(km_h = 5.3)%>%
  mutate(type = "SW")
```

#Session 3
```{r}
WGSP04_S3SUB <- WGSP04_S3SUB%>%
  mutate(session = 3)%>%
  mutate(participant = "P4")%>%
  mutate(BFR = "YES")%>%
  mutate(AOP = 102)%>%
  mutate(speed = "FW")%>%
  mutate(km_h = 6.8)%>%
  mutate(type = "FWBFR")
```

#Sesion 4
```{r}
WGSP04_S4SUB <- WGSP04_S4SUB%>%
  mutate(session = 4)%>%
  mutate(participant = "P4")%>%
  mutate(BFR = "NO")%>%
  mutate(AOP = 0)%>%
  mutate(speed = "FW")%>%
  mutate(km_h = 6.8)%>%
  mutate(type = "FW")
```

```{r}
WGSP04SUB <- rbind(WGSP04_S1SUB,WGSP04_S2SUB,WGSP04_S3SUB,WGSP04_S4SUB)
```

#WGSP06
```{r}
WGSP06_S1SUB <- read.csv("C://Users//thoma//OneDrive - Murdoch University//Desktop//PhD 2021//Study 2 and 3//AAADATA//Participants//WGSP06//Session1//Perceptual//sub_measures.CSV")
WGSP06_S2SUB <- read.csv("C://Users//thoma//OneDrive - Murdoch University//Desktop//PhD 2021//Study 2 and 3//AAADATA//Participants//WGSP06//Session2//Perceptual//sub_measures.CSV")
WGSP06_S3SUB <- read.csv("C://Users//thoma//OneDrive - Murdoch University//Desktop//PhD 2021//Study 2 and 3//AAADATA//Participants//WGSP06//Session3//Perceptual//sub_measures.CSV")
WGSP06_S4SUB <- read.csv("C://Users//thoma//OneDrive - Murdoch University//Desktop//PhD 2021//Study 2 and 3//AAADATA//Participants//WGSP06//Session4//Perceptual//sub_measures.CSV")
```

#Session 1
```{r}
WGSP06_S1SUB <- WGSP06_S1SUB%>%
 mutate(session = 1)%>%
  mutate(participant = "P6")%>%
  mutate(BFR = "YES")%>%
  mutate(AOP = 115)%>%
  mutate(speed = "SW")%>%
  mutate(km_h = 5.3)%>%
  mutate(type = "SWBFR")
```

#Session 2
```{r}
WGSP06_S2SUB <- WGSP06_S2SUB%>%
  mutate(session = 2)%>%
  mutate(participant = "P6")%>%
   mutate(BFR = "NO")%>%
  mutate(AOP = 0)%>%
  mutate(speed = "SW")%>%
  mutate(km_h = 5.3)%>%
mutate(type = "SW")
```

#Session 3
```{r}
WGSP06_S3SUB <- WGSP06_S3SUB%>%
  mutate(session = 3)%>%
  mutate(participant = "P6")%>%
  mutate(BFR = "YES")%>%
  mutate(AOP = 115)%>%
  mutate(speed = "FW")%>%
  mutate(km_h = 6.8)%>%
  mutate(type = "FWBFR")
```

#Sesion 4
```{r}
WGSP06_S4SUB <- WGSP06_S4SUB%>%
  mutate(session = 4)%>%
  mutate(participant = "P6")%>%
  mutate(BFR = "NO")%>%
  mutate(AOP = 0)%>%
  mutate(speed = "FW")%>%
  mutate(km_h = 6.8)%>%
  mutate(type = "FW")
```

```{r}
WGSP06SUB <- rbind(WGSP06_S1SUB,WGSP06_S2SUB,WGSP06_S3SUB,WGSP06_S4SUB)
```

#Participant Bind
```{r}
SUBMEASURES <- rbind(WGSP01SUB, WGSP02SUB,WGSP03SUB,WGSP04SUB,WGSP06SUB)
```

#Summary
```{r}
RPESUM <- SUBMEASURES%>%
summarySE(measurevar = "RPE", groupvar =c("type"), na.rm = TRUE, conf.interval = 0.95, .drop = TRUE)
  #filter(!INTERVALS %in% "BLANK")
```

